### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by mertcangokgoz** [0x27/TheItalianJob#1]
Hello. I try to use hackingteam hunter an always have the same error: Error: Unable to parse JSON response.

Error: Unable to parse JSON response

**Comment by 0x27** [comment]
This is a serverside issue over at Shodan, most likely. Also, have you added your Shodan API key to the application?

**Comment by mertcangokgoz** [comment]
yes i added APİ key but shodan system error maybe shodan system issue ,i dont know
